ci: disable failing integration tests
googlemaps/flutter-navigation-sdk pull request #166
Opened 2024-10-01 06:30 UTC by jokerttu

This PR temporarily disables the failing integration tests to unblock other work. The process of fixing and re-enabling these tests is being tracked in https://github.com/googlemaps/flutter-navigation-sdk/pull/105

2024-10-01 07:06 UTC, vesse0 approved these changes

2024-10-01 09:38 UTC, wangela requested changes

2024-10-01 09:38 UTC, wangela commented on .github/workflows/integration_tests.yaml
Why remove the integration tests? We have a workaround for community-contributed PRs which is to override the checks as long as integration tests pass locally on the reviewer and the author's marchines.

2024-10-02 06:31 UTC, jokerttu commented on .github/workflows/integration_tests.yaml
Let's close this and merge https://github.com/googlemaps/flutter-navigation-sdk/pull/105 instead even when it's failing time to time.
It's still fixes unit tests.
I'll file new issue for fixing failing flaky integration tests

2024-10-02 06:31 UTC, closed without merging