ci: update release-please action and config
googlemaps/flutter-navigation-sdk pull request #201
Opened 2024-11-04 13:22 UTC by jokerttu

Update release please CI action script and configurations

2024-11-19 21:00 UTC, wangela requested changes

2024-11-19 21:00 UTC, wangela commented on .release-please-manifest.json
Let's establish that the initial version for this manifest is 0.4.0, similar to https://github.com/googlemaps/google-maps-ios-utils/blob/main/.release-please-manifest.json

2024-11-19 21:00 UTC, wangela commented on release-please-config.json
See https://github.com/googlemaps/google-maps-ios-utils/blob/main/release-please-config.json for example config.

- Bootstrap SHA should be the commit related to the 0.4.0 release, i.e. 19d2491ea1a03add016b31b94562da03ccefaa74
- Based on [configfile README](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile) I agree `bump-minor-pre-major` should be true for this pre-1.0 package
- Let's raise `bump-minor-pre-major` should be one level to be same level as `include-component-in-tag`
- Specify the `changelog-path` for the package

2024-11-22 06:48 UTC, jokerttu commented on CHANGELOG.md
This PR also reorders the changelog items to proper order.

2024-11-29 04:46 UTC, caio1985 approved these changes
LGTM

2024-11-29 05:56 UTC, illuminati1911 approved these changes
LGTM

2024-11-29 06:34 UTC, merged